apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: mediasync-night
  namespace: mediasync
spec:
  schedule: "5 3 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: mediasync
            image: mansm/mediasync
            # args:
            #   - /bin/bash
            #   - -c 
            #   - sleep 290
            env:
              - name: MEDIASYNC_CONF
                value: "/etc/mediasync-settings.yaml"
              - name: MEDIASYNC_DBLOC
                value: "/var/data/media.db"
            volumeMounts:
              - mountPath: "/var/data/"
                name: mediasync-data
              - mountPath: /etc/mediasync-settings.yaml
                name: mediasync-config
                subPath: settings.yaml
          restartPolicy: OnFailure
          volumes:
            - name: mediasync-data
              persistentVolumeClaim:
                claimName: mediasync-data
            - name: mediasync-config
              secret:
                secretName: mediasync-config
                #defaultMode: 256