apiVersion: v1
kind: PersistentVolume
metadata:
  name: mediasync-data
  namespace: mediasync
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  persistentVolumeReclaimPolicy: Retain
  iscsi:
    iqn: iqn.2000-01.com.synology:DiskStation.Target-1.u
    targetPortal: 10.0.2.4
    lun: 3

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mediasync-data
  namespace: mediasync
spec:
  volumeName: mediasync-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
