apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-alertmanager
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  persistentVolumeReclaimPolicy: Retain
  iscsi:
    iqn: iqn.2000-01.com.synology:DiskStation.Target-1.9cbabe8c8b
    targetPortal: 10.0.1.2
    lun: 2

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-alertmanager
  namespace: monitoring
spec:
  volumeName: prometheus-alertmanager
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi